# Nginx
#
# VERSION 0.0.1

ARG VERSION=latest
FROM nginx:$VERSION
LABEL maintainer "Dmitri G."

# Working directory initialization
# WORKDIR /root/

# Add some config files
COPY [".bashrc","/root/"]

